name: levy
description: "An app to find a perfect bus"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  levy_address:
    path: ../levy_address

  levy_dependencies:
    path: ../levy_dependencies
#    git:
#      url: https://github.com/andreleitejr/levy_dependencies.git

  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  injectable: ^2.5.0
  flutter_riverpod: ^2.5.3
  hooks_riverpod: ^2.5.4
  flutter_hooks: ^0.20.5
  get_it: ^8.0.0
  rxdart: ^0.28.0
  auto_route: ^9.2.2
  auto_route_generator: ^9.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  slang: ^4.1.0
  slang_flutter: ^4.1.0
  flutter_svg: ^2.0.11
  numberpicker: ^2.1.2
  sqflite: ^2.4.1
  uuid: ^4.5.1
  path: ^1.9.0
  google_maps_flutter: ^2.10.0
  location: ^6.0.2
  geolocator: ^13.0.2
  widget_to_marker: ^1.0.6
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.2
  golden_toolkit: ^0.15.0
  sqflite_common_ffi: ^2.3.4+4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
     - assets/icons/
     - assets/images/
     - .env
     - assets/fonts/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
