name: levy
description: "An app to find a perfect bus"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  injectable: ^2.5.0
  flutter_riverpod: ^2.5.3
  hooks_riverpod: ^2.5.4
  flutter_hooks: ^0.20.5
  get_it: ^8.0.0
  rxdart: ^0.28.0
  auto_route: ^9.2.2
  auto_route_generator: ^9.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  slang: ^4.1.0
  slang_flutter: ^4.1.0
  flutter_svg: ^2.0.11
  numberpicker: ^2.1.2
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
     - assets/icons/
     - assets/images/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
